---
title: '12_merge_weather_stations_data'
date: "18.Aug.2025"
date-modified: "today"
date-format: "DD.MMM.YYYY"
execute:
  echo: true
  warning: false
  #message: false

from: markdown+emoji
categories: [snakemake, rounding_numbers]
toc: true
toc-title: "Index"
smooth-scroll: true
toc-depth: 3
#fig-dpi: 300
format:
  html:
    embed-resources: true
    df-print: kable
    page-layout: full
    #code-overflow: wrap
    fig-width: 8
    fig-height: 6
code-line-numbers: true
number-sections: true
## to wrap output
include-in-header:
  - text: |
      <style>
      .cell-output-stdout code {
        word-break: break-wor !important;
        white-space: pre-wrap !important;
      }
      </style>
---

```{r}
#| label: setup
#| echo: false

all_times <- list()  # store the time for each chunk

knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res <- difftime(Sys.time(), now, units = "mins")
      all_times[[options$label]] <<- res
    }
  }
})
)

knitr::opts_chunk$set(
  # don't use, has issues with a lot of symbols
  # https://yihui.org/formatr/
  #tidy = TRUE,
  time_it = TRUE,
  fig.align = 'center',
  highlight = TRUE, 
  cache.lazy = FALSE,
  #comment = "#>",
  collapse = TRUE
)

## to crop the empty white space around the pdf plots
knitr::knit_hooks$set(crop = knitr::hook_pdfcrop)
```

```{r}
#| label: libraries_packages
#| output: false

## conda env: ./env_tar/smk_env1/

x <- c("tidyverse", "magrittr")

## Load libraries
invisible(lapply(x, library, character.only = TRUE))
```


# load data

```{r}

prcp_data <- read_tsv("../data/9_ghcnd_tidy.tsv.gz") %T>% 
  {head(.) %>% print()} %T>%
  {dim(.) %>% print()} 

station_data <- read_tsv("../data/11_ghcnd_regions_years.tsv") %T>% 
  {head(.) %>% print()} %T>%
  {dim(.) %>% print()} 
```

# test joining

```{r}
inner_join(prcp_data, 
           station_data,
           by = "id") %T>%
  {head(.) %>% print()}

## what about the data without correspondence?

## values in "prcp_data" not in "station_data"
anti_join(prcp_data, 
          station_data,
          by = "id") %T>% 
  {head(.) %>% print()} %>%
  {dim(.) %>% print()} 
## very few missing data for those stations (3 out of 3.269.055)

## values in "station_data" not in "prcp_data"
anti_join(station_data,
          prcp_data,
          by = "id") %T>% 
  {head(.) %>% print()} %>%
  {dim(.) %>% print()} 
## same (675 out of 127.608)

## come back to comb through these values if you see wholes in the map at the end 
```


# Summarize mean precipitation by region and year

Remove partial data (where the year is not whole)

```{r}
## remove stations where you have partial data BUT keep the last year you have on record

## what is the last year?
last_yr <- inner_join(prcp_data, 
           station_data,
           by = "id") %>%  
  arrange(desc(year)) %>% 
  slice_head(n=1) %>% 
  pull(year) 


lat_log_prcp <- inner_join(prcp_data, 
           station_data,
           by = "id") %T>% 
  {head(.) %>% print()} %T>%
  {dim(.) %>% print()} %>% 
  filter( (year != first_year & year != last_year) | year == last_yr) %>% 
  ## group by region; add the rest of the variables to keep them
  ## region is not really necessary in this analysis
  #group_by(region, latitude, longitude, year) %>% 
  group_by(latitude, longitude, year) %>% 
  summarize(mean_prcp = mean(prcp)) %T>%
  {head(.) %>% print()} %T>%
  {dim(.) %>% print()} %>% 
  
  ## from how many locations do we have data?
  summarize(n = n()) %T>%
  {head(.) %>% print()} %T>%
  {dim(.) %>% print()} 
```

# result exploration

## basic plotting

There is a bimodal distribution

```{r}
lat_log_prcp %>% 
  ggplot(aes(x=n)) + 
  geom_histogram()
```

##

```{r}

## how many stations with more than 100 observations
lat_log_prcp %>% 
  filter(n >= 100) %T>%
  {head(.) %>% print()} %>% 
  dim()

```


## synthesize the distribution of the data for each weather station


# Save time

```{r}
#| label: save_times

t(as.data.frame(all_times))
```

# Session information

```{r}
#| label: sessionInfo

sessionInfo()
```
